### ISSUE TITLE
Where is the .sql file?

### ISSUE THREAD

**Issue by mathewmoira** [sumeshmani/hrm#1]

**Comment by sumeshmani** [comment]
Will upload asap latest by tommorrow

**Comment by surendersingal** [comment]
Please upload sql file

**Comment by sumonbpkw** [comment]
still no sql files

**Comment by sumeshmani** [comment]
-- phpMyAdmin SQL Dump
-- version 3.2.0.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 24, 2018 at 04:11 PM
-- Server version: 5.1.37
-- PHP Version: 5.3.0

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `sftl_hrm`
--

-- --------------------------------------------------------

--
-- Table structure for table `attendance_adjustment`
--

CREATE TABLE IF NOT EXISTS `attendance_adjustment` (
  `attendance_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) NOT NULL,
  `short_dur` varchar(250) NOT NULL,
  `month` varchar(250) NOT NULL,
  `year` varchar(250) NOT NULL,
  `absent` varchar(250) NOT NULL,
  `closed_status` binary(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`attendance_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `attendance_adjustment`
--


-- --------------------------------------------------------

--
-- Table structure for table `attendance_lock`
--

CREATE TABLE IF NOT EXISTS `attendance_lock` (
  `attendance_lockId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `attendance_dateFrom` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `attendance_dateTo` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `attendance_lockMonth` varchar(10) NOT NULL,
  `attendance_lockYear` varchar(10) NOT NULL,
  `attendance_lockStatus` binary(1) NOT NULL DEFAULT 'Y',
  `attendance_lockedBy` varchar(250) NOT NULL,
  `attendance_lockedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`attendance_lockId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `attendance_lock`
--


-- --------------------------------------------------------

--
-- Table structure for table `attendance_request`
--

CREATE TABLE IF NOT EXISTS `attendance_request` (
  `request_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `month` varchar(250) NOT NULL,
  `year` varchar(250) NOT NULL,
  `request_type` varchar(250) NOT NULL,
  `request_days` varchar(250) NOT NULL,
  `request_hours` varchar(250) NOT NULL,
  `request_minutes` varchar(250) NOT NULL,
  `requested_by` bigint(20) NOT NULL,
  `request_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_status` binary(1) NOT NULL DEFAULT 'P',
  `approved_by1` int(11) NOT NULL,
  `approved_time1` datetime NOT NULL,
  `approved_status1` varchar(250) NOT NULL DEFAULT 'Pending',
  `approved_by2` int(11) NOT NULL,
  `approved_time2` int(11) NOT NULL,
  `approved_status2` varchar(250) NOT NULL DEFAULT 'Pending',
  `approved_file` binary(1) NOT NULL DEFAULT 'P',
  `request_remarks` text NOT NULL,
  `approval_remarks` text NOT NULL,
  PRIMARY KEY (`request_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `attendance_request`
--


-- --------------------------------------------------------

--
-- Table structure for table `attendance_summary`
--

CREATE TABLE IF NOT EXISTS `attendance_summary` (
  `Attendance_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Attendance_Month` varchar(250) NOT NULL,
  `Attendance_Year` varchar(250) NOT NULL,
  `Attendance_UserId` bigint(250) NOT NULL,
  `Attendance_McPresentDays` varchar(250) NOT NULL,
  `Attendance_McFriDay` varchar(250) NOT NULL,
  `Attendance_McDedMins` varchar(250) NOT NULL,
  `Attendance_McOtMins` varchar(250) NOT NULL,
  `Attendance_McAbsent` varchar(250) NOT NULL,
  `Attendance_ManPresentDay` varchar(250) NOT NULL,
  `Attendance_ManDedMins` varchar(250) NOT NULL,
  `Attendance_ManOtMins` varchar(250) NOT NULL,
  `Attendance_SalaryTotDays` varchar(250) NOT NULL,
  `Attendance_SalaryDays` varchar(250) NOT NULL,
  `Attendance_SalaryAbsentDays` varchar(250) NOT NULL,
  `Attendance_SalaryOtMins` varchar(250) NOT NULL,
  `Attendance_SalaryDedMins` varchar(250) NOT NULL,
  `Attendance_Remarks` text NOT NULL,
  `Attendance_Status` binary(1) NOT NULL DEFAULT 'Y',
  `Attendance_Editedby` varchar(250) NOT NULL,
  `Attendance_EditedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Attendance_Approval` binary(1) NOT NULL DEFAULT 'N',
  `Attendance_PendingApproval` varchar(250) NOT NULL,
  `Attendance_SuggestedBy` varchar(250) NOT NULL,
  PRIMARY KEY (`Attendance_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `attendance_summary`
--


-- --------------------------------------------------------

--
-- Table structure for table `employee_request`
--

CREATE TABLE IF NOT EXISTS `employee_request` (
  `ER_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ER_Type` varchar(250) NOT NULL,
  `ER_ODType` varchar(250) NOT NULL,
  `ER_UserId` bigint(20) NOT NULL,
  `ER_EmployeeRemarks` text NOT NULL,
  `ER_Files` varchar(250) NOT NULL,
  `ER_RequestDate` date NOT NULL,
  `ER_RequestTimeIn` datetime NOT NULL,
  `ER_RequestTimeOut` datetime NOT NULL,
  `ER_RequestPaidStatus` varchar(250) NOT NULL,
  `ER_Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ER_Status` varchar(250) NOT NULL DEFAULT 'Pending',
  `ER_ApprovedTimeIn` datetime NOT NULL,
  `ER_ApprovedTimeOut` datetime NOT NULL,
  `ER_ApprovedPaidStatus` varchar(250) NOT NULL,
  `ER_DoneBy` bigint(20) NOT NULL,
  `ER_SupervisorRemarks` text NOT NULL,
  `ER_SupervisorApproval` varchar(250) NOT NULL DEFAULT 'Pending',
  `ER_SupervisorApprovedBy` bigint(20) NOT NULL,
  `ER_ApprovedBy` bigint(20) NOT NULL,
  `ER_ApprovalDate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ER_ManagerRemarks` varchar(250) NOT NULL,
  `ER_Customer` text NOT NULL,
  `ER_Purpose` text NOT NULL,
  `ER_Result` text NOT NULL,
  `ER_SupervisorPaidStatus` binary(1) NOT NULL,
  `ER_stimein` datetime NOT NULL,
  `ER_stimeout` datetime NOT NULL,
  `ER_admintimein` datetime NOT NULL,
  `ER_admintimeout` datetime NOT NULL,
  `ER_AdminRemarks` text NOT NULL,
  `ER_AdminApproval` varchar(250) NOT NULL DEFAULT 'Pending',
  `ER_AdminApprovedBy` bigint(20) NOT NULL,
  `ER_AdminPaidStatus` binary(1) NOT NULL,
  PRIMARY KEY (`ER_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `employee_request`
--


-- --------------------------------------------------------

--
-- Table structure for table `hr_document`
--

CREATE TABLE IF NOT EXISTS `hr_document` (
  `Document_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Document_UserId` bigint(20) NOT NULL,
  `Document_Type` varchar(250) NOT NULL,
  `Document_No` varchar(250) NOT NULL,
  `Document_IssueDate_En` date NOT NULL,
  `Document_ExpireDate_En` date NOT NULL,
  `Document_IssueDate_Ar` date NOT NULL,
  `Document_ExpireDate_Ar` date NOT NULL,
  `Document_UserName` varchar(250) NOT NULL,
  `Document_Dependant` varchar(250) NOT NULL DEFAULT 'Self',
  `Document_Image` text NOT NULL,
  `Document_Status` binary(1) NOT NULL DEFAULT 'Y',
  `UploadedBy` varchar(250) NOT NULL,
  `UploadedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Document_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `hr_document`
--


-- --------------------------------------------------------

--
-- Table structure for table `kpi_details`
--

CREATE TABLE IF NOT EXISTS `kpi_details` (
  `Kpi_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Kpi_MasterId` bigint(20) NOT NULL,
  `Kpi_SlNo` varchar(250) NOT NULL,
  `Kpi_Details` text NOT NULL,
  `Kpi_TotalScore` decimal(10,1) NOT NULL,
  `Kpi_SelfScore_1` decimal(10,1) NOT NULL,
  `Kpi_Group` bigint(250) NOT NULL,
  `Kpi_SelfScore_2` decimal(11,1) NOT NULL,
  `Kpi_PerDone1` decimal(10,1) NOT NULL,
  `Kpi_PerDone2` decimal(10,1) NOT NULL,
  `Kpi_DeptMangerScore1` decimal(10,1) NOT NULL,
  `Kpi_DeptMangerScore2` decimal(10,1) NOT NULL,
  `Kpi_AdminMangerScore` decimal(10,1) NOT NULL,
  `Kpi_GMScore` decimal(10,1) NOT NULL,
  `Kpi_FeedBack` text NOT NULL,
  `Kpi_Remarks1` text NOT NULL,
  `Kpi_Remarks2` text NOT NULL,
  `Kpi_Remarks3` text NOT NULL,
  `Kpi_Rem_UserId1` bigint(20) NOT NULL,
  `Kpi_Rem_UserId2` bigint(20) NOT NULL,
  `Kpi_Rem_UserId3` bigint(20) NOT NULL,
  `Kpi_FinalScore1` decimal(10,1) NOT NULL,
  `Kpi_FinalScore2` decimal(10,1) NOT NULL,
  `Kpi_FinalTotalScore` decimal(10,1) NOT NULL,
  `Kpi_GroupId` int(11) NOT NULL,
  PRIMARY KEY (`Kpi_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `kpi_details`
--


-- --------------------------------------------------------

--
-- Table structure for table `kpi_detailsmaster`
--

CREATE TABLE IF NOT EXISTS `kpi_detailsmaster` (
  `Kpi_DetailsId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Kpi_Details` varchar(250) NOT NULL,
  `Kpi_Dept` varchar(250) NOT NULL,
  `Kpi_Group` varchar(250) NOT NULL,
  PRIMARY KEY (`Kpi_DetailsId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `kpi_detailsmaster`
--


-- --------------------------------------------------------

--
-- Table structure for table `kpi_group`
--

CREATE TABLE IF NOT EXISTS `kpi_group` (
  `kpi_GroupId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `kpi_GroupVersion` varchar(250) NOT NULL,
  `kpi_GroupName` varchar(250) NOT NULL,
  `kpi_GroupRemarks` varchar(250) NOT NULL,
  `kpi_GroupParentId` bigint(20) NOT NULL DEFAULT '0',
  `kpi_NumRows` int(11) NOT NULL,
  `kpi_MaxScore` decimal(20,2) NOT NULL,
  `kpi_GroupEditStatus` binary(1) NOT NULL DEFAULT '0',
  `kpi_GroupProfile` int(11) NOT NULL,
  PRIMARY KEY (`kpi_GroupId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `kpi_group`
--


-- --------------------------------------------------------

--
-- Table structure for table `kpi_master`
--

CREATE TABLE IF NOT EXISTS `kpi_master` (
  `Kpi_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Kpi_UserId` bigint(20) NOT NULL,
  `Kpi_Year` int(11) NOT NULL,
  `Kpi_SupervisorId` int(11) NOT NULL,
  `Kpi_ManagerId` int(11) NOT NULL,
  `Kpi_AdminId` int(11) NOT NULL,
  `Kpi_Grade` varchar(250) NOT NULL,
  `Kpi_Designation` varchar(250) NOT NULL,
  `Kpi_Department` varchar(250) NOT NULL,
  `Kpi_Profile` int(11) NOT NULL,
  `Kpi_Status` varchar(250) NOT NULL DEFAULT 'Pending',
  `Kpi_Recommend` text NOT NULL,
  PRIMARY KEY (`Kpi_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `kpi_master`
--


-- --------------------------------------------------------

--
-- Table structure for table `kpi_remarks`
--

CREATE TABLE IF NOT EXISTS `kpi_remarks` (
  `kpi_remarksid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `kpi_detailsid` bigint(20) NOT NULL,
  `kpi_userid` bigint(20) NOT NULL,
  `kpi_half` varchar(250) NOT NULL,
  `kpi_currentstatus` text NOT NULL,
  `kpi_actionsplanned` text NOT NULL,
  `kpi_actionsplan` text NOT NULL,
  `kpi_whentoachieve` text NOT NULL,
  `kpi_supervisorremarks` text NOT NULL,
  `kpi_managerremarks` text NOT NULL,
  `kpi_remarkslock` varchar(250) NOT NULL,
  PRIMARY KEY (`kpi_remarksid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `kpi_remarks`
--


-- --------------------------------------------------------

--
-- Table structure for table `ncr_user`
--

CREATE TABLE IF NOT EXISTS `ncr_user` (
  `User_Division` varchar(250) NOT NULL,
  `User_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `User_EmployeeCode` varchar(250) NOT NULL,
  `User_AttenId` varchar(250) NOT NULL,
  `User_FullName` varchar(250) NOT NULL,
  `User_Name` varchar(250) NOT NULL,
  `User_NameAr` varchar(250) NOT NULL,
  `User_LoginName` varchar(250) NOT NULL,
  `User_Email` varchar(250) NOT NULL,
  `User_Nationality` varchar(250) NOT NULL,
  `User_Grade` varchar(250) NOT NULL,
  `User_Designation` varchar(250) NOT NULL,
  `User_Department` varchar(250) NOT NULL,
  `User_ManagerId` varchar(250) NOT NULL,
  `User_SupervisorId` varchar(250) NOT NULL,
  `User_ManagerStatus` binary(1) NOT NULL DEFAULT 'N',
  `User_SupervisorStatus` binary(1) NOT NULL DEFAULT 'N',
  `User_AdminStatus` binary(1) NOT NULL DEFAULT 'N',
  `User_JoiningDate` datetime NOT NULL,
  `User_LeavingDate` date NOT NULL,
  `User_KpiStatus` binary(1) NOT NULL DEFAULT 'Y',
  `User_Password` varchar(250) NOT NULL,
  `User_Status` varchar(1) NOT NULL DEFAULT 'N',
  `User_NcrStatus` binary(1) NOT NULL DEFAULT 'R',
  `User_StandardDesignStatus` binary(1) NOT NULL DEFAULT 'R',
  `User_OfferStatus` binary(1) NOT NULL DEFAULT 'R',
  `User_FlowStatus` binary(1) NOT NULL DEFAULT 'U',
  `User_POStatus` binary(1) NOT NULL DEFAULT 'R',
  `User_WorkHours` varchar(20) NOT NULL DEFAULT '12',
  `User_ShiftId` bigint(20) NOT NULL,
  `Vacation_Id` varchar(250) NOT NULL,
  `User_Sponsor` varchar(250) NOT NULL,
  PRIMARY KEY (`User_Id`),
  UNIQUE KEY `User_Name` (`User_Name`),
  UNIQUE KEY `User_Loginname` (`User_LoginName`),
  UNIQUE KEY `User_Name_2` (`User_Name`),
  UNIQUE KEY `User_Name_3` (`User_Name`),
  UNIQUE KEY `User_AttenId` (`User_AttenId`),
  UNIQUE KEY `User_EmployeeCode` (`User_EmployeeCode`),
  UNIQUE KEY `User_AttenId_4` (`User_AttenId`),
  KEY `User_AttenId_2` (`User_AttenId`),
  KEY `User_AttenId_3` (`User_AttenId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `ncr_user`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_allowance`
--

CREATE TABLE IF NOT EXISTS `payroll_allowance` (
  `allowance_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `allowance_name` varchar(250) NOT NULL,
  `allowance_add` varchar(250) NOT NULL,
  `allowance_fixed` varchar(250) NOT NULL,
  `allowance_amount` varchar(250) NOT NULL,
  `allowance_percentage` varchar(250) NOT NULL,
  `variable_dependent` varchar(250) NOT NULL,
  `allowance_schedule` varchar(250) NOT NULL,
  `Allowance_EffectiveFrom` date NOT NULL,
  `Allowance_EffectiveTo` date NOT NULL,
  `last_paid` date NOT NULL,
  `next_scheduled` date NOT NULL,
  `created_by` varchar(250) NOT NULL,
  `creation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`allowance_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_allowance`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_allowancemaster`
--

CREATE TABLE IF NOT EXISTS `payroll_allowancemaster` (
  `allowance_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `allowance_name` varchar(250) NOT NULL,
  PRIMARY KEY (`allowance_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_allowancemaster`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_allowancesummary`
--

CREATE TABLE IF NOT EXISTS `payroll_allowancesummary` (
  `payroll_allowance_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `payroll_id` bigint(20) NOT NULL,
  `payroll_allowance_name` varchar(250) NOT NULL,
  `payroll_amount` varchar(250) NOT NULL,
  `last_paid` date NOT NULL,
  `next_scheduled` date NOT NULL,
  PRIMARY KEY (`payroll_allowance_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_allowancesummary`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_bankdetails`
--

CREATE TABLE IF NOT EXISTS `payroll_bankdetails` (
  `payroll_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `payroll_userid` varchar(250) NOT NULL,
  `effective_from` date NOT NULL DEFAULT '2013-01-01',
  `effective_to` date NOT NULL DEFAULT '2099-03-31',
  `payroll_bankname` varchar(250) NOT NULL,
  `payroll_bankcode` varchar(250) NOT NULL,
  `payroll_iban` varchar(250) NOT NULL,
  `payroll_accountname` varchar(250) NOT NULL,
  `payroll_accountno` varchar(250) NOT NULL,
  `created_by` varchar(250) NOT NULL,
  `creation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payroll_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_bankdetails`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_basic`
--

CREATE TABLE IF NOT EXISTS `payroll_basic` (
  `basic_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(250) NOT NULL,
  `basic_amount` varchar(250) NOT NULL,
  `effective_from` datetime NOT NULL,
  `effective_to` datetime NOT NULL,
  `status` binary(1) NOT NULL DEFAULT 'Y',
  `increment` varchar(250) NOT NULL,
  `created_by` varchar(250) NOT NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`basic_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_basic`
--


-- --------------------------------------------------------

--
-- Table structure for table `payroll_summary`
--

CREATE TABLE IF NOT EXISTS `payroll_summary` (
  `payroll_summaryid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `payroll_month` int(11) NOT NULL,
  `payroll_year` int(11) NOT NULL,
  `payroll_userid` bigint(20) NOT NULL,
  `shift_hours` varchar(250) NOT NULL,
  `tot_days` int(11) NOT NULL,
  `present_days` varchar(250) NOT NULL,
  `absent_days` varchar(250) NOT NULL,
  `ded_minutes` varchar(250) NOT NULL,
  `ot_minutes` varchar(250) NOT NULL,
  `basic_pay` varchar(250) NOT NULL,
  `net_basicamount` varchar(250) NOT NULL,
  `ded_amount` varchar(250) NOT NULL,
  `ot_amount` varchar(250) NOT NULL,
  `net_total` varchar(250) NOT NULL,
  `net_totalallowance` varchar(250) NOT NULL,
  `net_totaldeduction` varchar(250) NOT NULL,
  `created_by` bigint(20) NOT NULL,
  `creation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payroll_summaryid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `payroll_summary`
--


-- --------------------------------------------------------

--
-- Table structure for table `sftl_attendance`
--

CREATE TABLE IF NOT EXISTS `sftl_attendance` (
  `Attendance_Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `Attendance_UserId` bigint(20) NOT NULL,
  `Attendance_AttenId` varchar(250) NOT NULL,
  `AttendanceCardNo` varchar(250) NOT NULL,
  `Attendance_UserName` varchar(250) NOT NULL,
  `Attendance_McInTime` datetime NOT NULL,
  `Attendance_McOutTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Attendance_Paid` varchar(250) NOT NULL,
  `Attendance_NonPaid` varchar(250) NOT NULL,
  PRIMARY KEY (`Attendance_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `sftl_attendance`
--


-- --------------------------------------------------------

--
-- Table structure for table `sftl_holidays`
--

CREATE TABLE IF NOT EXISTS `sftl_holidays` (
  `Holiday_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Holiday_Name` varchar(250) NOT NULL,
  `Holiday_Starts` datetime NOT NULL,
  `Holiday_Ends` datetime NOT NULL,
  `Holiday_Dep` varchar(250) NOT NULL,
  PRIMARY KEY (`Holiday_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `sftl_holidays`
--


-- --------------------------------------------------------

--
-- Table structure for table `sftl_number`
--

CREATE TABLE IF NOT EXISTS `sftl_number` (
  `Number_Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `Number_Type` varchar(250) NOT NULL,
  `Number_Value` varchar(250) NOT NULL,
  PRIMARY KEY (`Number_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `sftl_number`
--


-- --------------------------------------------------------

--
-- Table structure for table `sftl_vacation`
--

CREATE TABLE IF NOT EXISTS `sftl_vacation` (
  `Vacation_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Vacation_UserId` varchar(250) NOT NULL,
  `Vacation_Year` varchar(250) NOT NULL,
  `Vacation_StartDate` datetime NOT NULL,
  `Vacation_EndDate` datetime NOT NULL,
  `Vacation_ApprovedBy` int(11) NOT NULL,
  `Vacation_ApprovedDate1` datetime NOT NULL,
  `Vacation_ApprovedDate2` datetime NOT NULL,
  `Vacation_Status` varchar(250) NOT NULL,
  `Vacation_UserRemarks` text NOT NULL,
  `Vacation_SupervsiorRemarks` text NOT NULL,
  `Vacation_ManagerRemarks` text NOT NULL,
  `Vacation_AdminRemarks` text NOT NULL,
  `Vacation_Remarks` text NOT NULL,
  `Vacation_changes` text NOT NULL,
  PRIMARY KEY (`Vacation_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `sftl_vacation`
--


-- --------------------------------------------------------

--
-- Table structure for table `shift_details`
--

CREATE TABLE IF NOT EXISTS `shift_details` (
  `Shift_DetailsId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Shift_EnteredBy` bigint(20) NOT NULL,
  `Shift_EmployeeId` bigint(20) NOT NULL,
  `Shift_StartTime` datetime NOT NULL,
  `Shift_EndTime` datetime NOT NULL DEFAULT '2999-12-31 00:00:00',
  `Shift_MasterId` bigint(20) NOT NULL,
  `Shift_Status` binary(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`Shift_DetailsId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `shift_details`
--


-- --------------------------------------------------------

--
-- Table structure for table `shift_master`
--

CREATE TABLE IF NOT EXISTS `shift_master` (
  `Shift_Id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Shift_Name` varchar(250) NOT NULL,
  `Shift_InTime` varchar(250) NOT NULL,
  `Shift_OutTime` varchar(250) NOT NULL,
  `Shift_OffDays` varchar(250) NOT NULL,
  `Shift_Status` binary(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`Shift_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `shift_master`
--


-- --------------------------------------------------------

--
-- Table structure for table `vacation_master`
--

CREATE TABLE IF NOT EXISTS `vacation_master` (
  `Vacation_MasterId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Vacation_Days` varchar(250) NOT NULL,
  `Vacation_Interval` varchar(250) NOT NULL,
  `Vacation_Remarks` varchar(250) NOT NULL,
  `Vacataion_Status` varchar(250) NOT NULL,
  PRIMARY KEY (`Vacation_MasterId`),
  UNIQUE KEY `Vacation_MasterId` (`Vacation_MasterId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `vacation_master`
--


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
